services:
  - type: web
    name: hit4power
    runtime: python             # 'env' is deprecated; use 'runtime'
    plan: pro                   # Professional plan so disks are allowed
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SESSION_SECRET
        generateValue: true
      - key: INSTRUCTOR_CODE
        value: CHANGE_ME_MASTER_CODE
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
